In [128]:
import numpy as np

In [129]:
#0D Array
arr_0d=np.array(1)
print(arr_0d)

1


In [130]:
#1D Array
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [131]:
#2D Array
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [132]:
#3D Array
arr_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [133]:
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [134]:
#Arrays of zeros
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [135]:
#Array of ones
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [136]:
#Array of Randon Values
random_arr=np.random.random((2,3))
print(random_arr)

[[0.87858047 0.5849599  0.73271956]
 [0.69485705 0.71989954 0.81780579]]


In [137]:
#Identity Matrix
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [138]:
#Array with a range values
range_arr=np.arange(0,10,2) #Start Stop Step
print(range_arr)

[0 2 4 6 8]


In [139]:
#Array Attributes
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

Each greenhouse has sensors that record temperature (°C) readings at different times of the day.

You received the following data:

Your tasks are:

Create NumPy arrays

Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.

Print the array.

In [140]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)

[[22 25 20]
 [24 26 23]]


Check array properties

Print the shape, size, data type, and number of dimensions of temp_data.

In [141]:
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data type:",temp_data.dtype)
print("Number of dimensions:",temp_data.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


Add a third greenhouse

The third greenhouse (GH3) records [21, 23, 22].

In [142]:
GH3=np.array([21,23,22])
print(GH3)

[21 23 22]


Create a new array updated_temp_data that includes all three greenhouses.

In [143]:
updated_temp_data=np.array([[22,25,20],[24,26,23],[21,23,22]])
print(updated_temp_data)

[[22 25 20]
 [24 26 23]
 [21 23 22]]


Generate supporting data

Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).

Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.

In [144]:
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)

greenhouse_identity=np.eye(3)
print(greenhouse_identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Display all arrays

Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [145]:
print("Update temp data")
print(updated_temp_data)
print("Sensor_error_flags")
print(sensor_error_flags)
print("greenhouse_identity")
print(greenhouse_identity)

Update temp data
[[22 25 20]
 [24 26 23]
 [21 23 22]]
Sensor_error_flags
[[0. 0. 0.]
 [0. 0. 0.]]
greenhouse_identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [146]:
#Array Indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,-1])

2
6


In [147]:
#Array Slicing
print(arr[:,1:])

[[2 3]
 [5 6]]


Indexing and Slicing:

You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:

Each row represents a type of fruit.

Each column represents a day of the week (Mon–Sun).

Create the 2D NumPy array

Create an array named shipments using the above data.

In [148]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,65,70,75]])
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 65 70 75]]


Access single elements (Indexing):

Get the number of Apples shipped on Wednesday.

Get the number of Oranges shipped on Sunday.

In [149]:
print("Number of Apples on Wednesday")
print(shipments[0,2])
print("Number of oranges on Sunday")
print(shipments[1,6])

Number of Apples on Wednesday
55
Number of oranges on Sunday
75


Access multiple elements (Slicing):

Extract all the weekday shipments (Mon–Fri) for all fruits.

Extract only the weekend shipments (Sat & Sun).

In [150]:
print("all the weekday shipments (Mon–Fri) for all fruits")
print(shipments[:,0:5])
print("shipments (Sat & Sun)")
print(shipments[:,5:7])

all the weekday shipments (Mon–Fri) for all fruits
[[50 60 55 70 65]
 [40 45 50 60 65]]
shipments (Sat & Sun)
[[80 90]
 [70 75]]



Extract the shipments of Apples from Wednesday to Saturday.

In [151]:
print("Apples from Wednesday to Saturday.")
print(shipments[0:1,2:6])

Apples from Wednesday to Saturday.
[[55 70 65 80]]


Bonus (Practice thinking):

Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [152]:
shipments[0,5]=100
print(shipments)

[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  65  70  75]]


ARRAY OPERATIONS



In [153]:
#Arithmetic operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition : ")
print(a+b)
print("Multiplication : ")
print(a*b)
print("Scalar Multiplication : ")
print(a*2)

Addition : 
[5 7 9]
Multiplication : 
[ 4 10 18]
Scalar Multiplication : 
[2 4 6]


MATRIX MULTIPLICATION

In [154]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result=np.dot(mat1,mat2)
print(result)

[[19 22]
 [43 50]]


BROADCASTING

Numpy autamatically applies Operations across arrays of different shapes when compatible

In [155]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


UNIVERSAL FUNCTIONS(ufuncs)

In [156]:
# Exponential and Logarithmic ufuncs
arr=np.array([1,2,3])
print(arr)
print("Exponentiation")
print(np.exp(arr))
print("Square root")
print(np.sqrt(arr))
print("Logarithm")
print(np.log(arr))

[1 2 3]
Exponentiation
[ 2.71828183  7.3890561  20.08553692]
Square root
[1.         1.41421356 1.73205081]
Logarithm
[0.         0.69314718 1.09861229]


In [157]:
# Arithmetic ufuncs
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]


In [158]:
# Trigonometric ufuncs
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[ 0. nan nan]
[0.78539816 1.10714872 1.24904577]
[ 57.29577951 114.59155903 171.88733854]
[0.01745329 0.03490659 0.05235988]


/tmp/ipython-input-1490931895.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
/tmp/ipython-input-1490931895.py:5: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [159]:
# Rounding ufuncs
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [160]:
# Statistical ufuncs
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))

1
3
2.0
0.816496580927726
0.6666666666666666
6
6


In [161]:
# Logical ufuncs
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x, y))

[ True  True  True]
[ True  True  True]
[False False False]
[False False False]


In [162]:
# Comparison ufuncs
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))

[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


In [163]:
# Bitwise ufuncs
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.invert(x))

[0 0 2]
[5 7 7]
[5 7 5]
[-2 -3 -4]


You are a data engineer at a renewable-energy company that runs 3 solar farms.

Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Create arrays

Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).

In [164]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])

Stack them into a single 3D array production_all of shape (3, 4, 3).

In [165]:
production_all=np.stack([farmA,farmB,farmC])
print(production_all)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]


Array attributes

Print the .shape, .size, .dtype, and .ndim of production_all.

In [166]:
print("Shape:",production_all.shape)
print("Size:",production_all.size)
print("Data type:",production_all.dtype)
print("Number of dimensions:",production_all.ndim)

Shape: (3, 4, 3)
Size: 36
Data type: int64
Number of dimensions: 3


Per-farm totals (arithmetic & aggregation)

Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).

In [167]:
total_per_farm=np.sum(production_all,axis=(1,2))
print(total_per_farm)

[126 234 174]


Compute mean, std, and var per farm.

In [173]:
mean_per_farm=np.mean(production_all,axis=(1,2))
print(mean_per_farm)
std_per_farm=np.std(production_all,axis=(1,2))
print(std_per_farm)
var_per_farm=np.var(production_all,axis=(1,2))
print(var_per_farm)

[10.5 20.  14.5]
[1.97905701 1.97905701 1.97905701]
[3.91666667 3.91666667 3.91666667]


Per-hour matrix multiplication idea (matrix op)

For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).

In [169]:
hour_weights=np.array([0.5,1.0,0.75])

Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)

In [170]:
weighted_per_panel1=np.dot(farmA,hour_weights)
print(weighted_per_panel1)
weighted_per_panel2=np.dot(farmB,hour_weights)
print(weighted_per_panel2)
weighted_per_panel3=np.dot(farmC,hour_weights)
print(weighted_per_panel3)

[25.25 23.   29.5  17.75]
[44.75 43.25 49.75 38.5 ]
[34.   31.25 38.5  26.75]


Broadcasting adjustments

The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).

In [172]:
production_all = production_all.astype(float)
production_all[1] += 0.5
print(production_all)

[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]


Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)

Compute a normalized version where you:

subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.

In [174]:
norm_data = (production_all - mean_per_farm[:, None, None]) / std_per_farm[:, None, None]
print("Normalized data shape:", norm_data.shape)


Normalized data shape: (3, 4, 3)


Apply many ufuncs (use the ufuncs listed previously)

Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:

Exponential family:

np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.

In [177]:
# Exponential family
exp_data = np.exp(norm_data)
expm1_data = np.expm1(norm_data)
log_data = np.log(np.abs(norm_data) + 1)  # avoid negatives
log10_data = np.log10(np.abs(norm_data) + 1)
log2_data = np.log2(np.abs(norm_data) + 1)
print("=== Exponential Family Functions ===")
print("exp_data (first farm):\n", exp_data[0])
print("expm1_data (first farm):\n", expm1_data[0])
print("log_data (first farm):\n", log_data[0])
print("log10_data (first farm):\n", log10_data[0])
print("log2_data (first farm):\n", log2_data[0])


=== Exponential Family Functions ===
exp_data (first farm):
 [[0.77674313 2.13386893 1.2874269 ]
 [0.46863235 1.2874269  0.77674313]
 [2.13386893 3.53681952 5.86216526]
 [0.2827399  0.17058543 0.46863235]]
expm1_data (first farm):
 [[-0.22325687  1.13386893  0.2874269 ]
 [-0.53136765  0.2874269  -0.22325687]
 [ 1.13386893  2.53681952  4.86216526]
 [-0.7172601  -0.82941457 -0.53136765]]
log_data (first farm):
 [[0.22525778 0.56414081 0.22525778]
 [0.56414081 0.22525778 0.22525778]
 [0.56414081 0.81679206 1.01831253]
 [0.81679206 1.01831253 0.56414081]]
log10_data (first farm):
 [[0.09782821 0.24500324 0.09782821]
 [0.24500324 0.09782821 0.09782821]
 [0.24500324 0.35472828 0.44224751]
 [0.35472828 0.44224751 0.24500324]]
log2_data (first farm):
 [[0.32497828 0.81388315 0.32497828]
 [0.81388315 0.32497828 0.32497828]
 [0.81388315 1.17838186 1.46911444]
 [1.17838186 1.46911444 0.81388315]]


Trigonometric:

np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.

In [178]:
# Trigonometric
sin_data = np.sin(norm_data)
cos_data = np.cos(norm_data)
tan_data = np.tan(norm_data)
arcsin_data = np.arcsin(np.clip(norm_data / np.max(np.abs(norm_data)), -1, 1))
arccos_data = np.arccos(np.clip(norm_data / np.max(np.abs(norm_data)), -1, 1))
arctan_data = np.arctan(norm_data)
deg_data = np.degrees(norm_data)
rad_data = np.radians(norm_data)

print("=== Trigonometric Functions (First Farm) ===")
print("sin_data:\n", sin_data[0])
print("cos_data:\n", cos_data[0])
print("tan_data:\n", tan_data[0])


=== Trigonometric Functions (First Farm) ===
sin_data:
 [[-0.24996642  0.68742445  0.24996642]
 [-0.68742445  0.24996642 -0.24996642]
 [ 0.68742445  0.95307252  0.98051646]
 [-0.95307252 -0.98051646 -0.68742445]]
cos_data:
 [[ 0.96825451  0.7262559   0.96825451]
 [ 0.7262559   0.96825451  0.96825451]
 [ 0.7262559   0.30274209 -0.19643692]
 [ 0.30274209 -0.19643692  0.7262559 ]]
tan_data:
 [[-0.2581619   0.946532    0.2581619 ]
 [-0.946532    0.2581619  -0.2581619 ]
 [ 0.946532    3.14813356 -4.99150805]
 [-3.14813356  4.99150805 -0.946532  ]]


Rounding:

np.round, np.floor, np.ceil, np.trunc.

In [179]:
#  Rounding functions
round_data = np.round(norm_data)
floor_data = np.floor(norm_data)
ceil_data = np.ceil(norm_data)
trunc_data = np.trunc(norm_data)

print("=== Rounding Functions (First Farm) ===")
print("Rounded:\n", round_data[0])
print("Floor:\n", floor_data[0])
print("Ceil:\n", ceil_data[0])
print("Trunc:\n", trunc_data[0])


=== Rounding Functions (First Farm) ===
Rounded:
 [[-0.  1.  0.]
 [-1.  0. -0.]
 [ 1.  1.  2.]
 [-1. -2. -1.]]
Floor:
 [[-1.  0.  0.]
 [-1.  0. -1.]
 [ 0.  1.  1.]
 [-2. -2. -1.]]
Ceil:
 [[-0.  1.  1.]
 [-0.  1. -0.]
 [ 1.  2.  2.]
 [-1. -1. -0.]]
Trunc:
 [[-0.  0.  0.]
 [-0.  0. -0.]
 [ 0.  1.  1.]
 [-1. -1. -0.]]


Comparison & logical ufuncs:

create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.

In [180]:
# Comparison & logical ufuncs
high_output = production_all > 20
even_hours_mask = np.array([False, True, False])  # even hours mask

logical_and = np.logical_and(high_output, even_hours_mask)
logical_or = np.logical_or(high_output, even_hours_mask)
logical_not = np.logical_not(high_output)
logical_xor = np.logical_xor(high_output, even_hours_mask)
greater_equal = np.greater_equal(production_all, 15)
less_than = np.less(production_all, 10)

print("=== Logical & Comparison Ufuncs ===")
print("High output mask:\n", high_output)
print("Greater_equal (>=15):\n", greater_equal[0])
print("Less_than (<10):\n", less_than[0])


=== Logical & Comparison Ufuncs ===
High output mask:
 [[[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False  True False]
  [ True  True  True]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]]
Greater_equal (>=15):
 [[False False False]
 [False False False]
 [False False False]
 [False False False]]
Less_than (<10):
 [[False False False]
 [ True False False]
 [False False False]
 [ True  True  True]]


Bitwise ufuncs (on integer arrays):

create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.

In [181]:
#Bitwise ufuncs
alerts = np.array([
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]],
    [[1,1,0],
     [0,1,0],
     [1,0,1],
     [1,0,0]],
    [[0,1,1],
     [1,0,1],
     [1,1,0],
     [0,0,1]]
], dtype=int)

bitwise_and = np.bitwise_and(alerts, (production_all.astype(int) % 2))
bitwise_or = np.bitwise_or(alerts, (production_all.astype(int) % 2))
bitwise_invert = np.invert(alerts)

print("=== Bitwise Operations (First Farm) ===")
print("Bitwise AND:\n", bitwise_and[0])
print("Bitwise OR:\n", bitwise_or[0])
print("Bitwise Invert:\n", bitwise_invert[0])


=== Bitwise Operations (First Farm) ===
Bitwise AND:
 [[0 0 1]
 [0 0 0]
 [0 1 0]
 [0 1 0]]
Bitwise OR:
 [[1 0 1]
 [1 1 1]
 [1 1 0]
 [0 1 1]]
Bitwise Invert:
 [[-2 -1 -2]
 [-1 -1 -2]
 [-2 -2 -1]
 [-1 -2 -1]]


Arithmetic ufuncs again:

np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.

Aggregations over ufunc outputs:

e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).

In [182]:
# Arithmetic ufuncs again
add_data = np.add(norm_data, 2)
sub_data = np.subtract(norm_data, 1)
mul_data = np.multiply(norm_data, 3)
div_data = np.divide(norm_data, 2)
power_data = np.power(norm_data, 2)
mod_data = np.mod(np.abs(norm_data), 1)

sum_exp = np.sum(np.exp(norm_data))
mean_sin = np.mean(np.sin(norm_data))

print("=== Arithmetic Ufuncs ===")
print("Add (first farm):\n", add_data[0])
print("Subtract (first farm):\n", sub_data[0])
print("Multiply (first farm):\n", mul_data[0])
print("Divide (first farm):\n", div_data[0])
print("Power (first farm):\n", power_data[0])
print("Mod (first farm):\n", mod_data[0])
print("\nSum of exp(normalized):", sum_exp)
print("Mean of sin(normalized):", mean_sin)


=== Arithmetic Ufuncs ===
Add (first farm):
 [[1.74735442 2.75793673 2.25264558]
 [1.24206327 2.25264558 1.74735442]
 [2.75793673 3.26322788 3.76851903]
 [0.73677212 0.23148097 1.24206327]]
Subtract (first farm):
 [[-1.25264558 -0.24206327 -0.74735442]
 [-1.75793673 -0.74735442 -1.25264558]
 [-0.24206327  0.26322788  0.76851903]
 [-2.26322788 -2.76851903 -1.75793673]]
Multiply (first farm):
 [[-0.75793673  2.27381019  0.75793673]
 [-2.27381019  0.75793673 -0.75793673]
 [ 2.27381019  3.78968364  5.3055571 ]
 [-3.78968364 -5.3055571  -2.27381019]]
Divide (first farm):
 [[-0.12632279  0.37896836  0.12632279]
 [-0.37896836  0.12632279 -0.12632279]
 [ 0.37896836  0.63161394  0.88425952]
 [-0.63161394 -0.88425952 -0.37896836]]
Power (first farm):
 [[0.06382979 0.57446809 0.06382979]
 [0.57446809 0.06382979 0.06382979]
 [0.57446809 1.59574468 3.12765957]
 [1.59574468 3.12765957 0.57446809]]
Mod (first farm):
 [[0.25264558 0.75793673 0.25264558]
 [0.75793673 0.25264558 0.25264558]
 [0.7579367

Broadcast-based summary table


Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.

In [183]:
#  Broadcast-based summary
panel_totals_per_farm = np.sum(production_all, axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

print("=== Panel Totals per Farm ===\n", panel_totals_per_farm)
print("Needs maintenance (per farm):", needs_maintenance)


=== Panel Totals per Farm ===
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Needs maintenance (per farm): [ True False  True]


Final KPIs (aggregation)

Compute:

overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [184]:
# Final KPIs
overall_total = np.sum(production_all)
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=(0, 2))

print("=== FINAL KPIs ===")
print("Overall total energy:", overall_total)
print("Peak hour value:", peak_value)
print("Peak at (Farm, Panel, Hour):", peak_index)
print("Average per panel across all farms:", average_per_panel)


=== FINAL KPIs ===
Overall total energy: 540.0
Peak hour value: 23.5
Peak at (Farm, Panel, Hour): (np.int64(1), np.int64(2), np.int64(1))
Average per panel across all farms: [15.5 14.5 17.5 12.5]


Reshaping Arrays

In [185]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


Stacking

In [189]:
a=np.array([1,2])
b=np.array([3,4])
#Vertical Stack
print(np.vstack((a,b)))
#Horizontal Stack
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


Splitting

In [190]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


ADVANCED INDEXING

In [191]:
#Boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
#Fancy indexing
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

[4 5]
[10 30]


Copy vs View

In [192]:
#View shares memory
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)

#Copy does not share memory
copy=arr.copy()
copy[0]=10
print(arr)

[10  2  3]
[10  2  3]


SAVING AND LOADING

In [193]:
#Save to a file
arr=np.array([1,2,3])
np.save('array.npy',arr)
#Load from a file
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


Create a 1D array of numbers from 10 to 50.


In [194]:
arr1=np.arange(10,51,1)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create a 3x3 array of random numbers between 0 and 1.

In [196]:
arr2=np.random.random((3,3))
print(arr2)

[[0.8697283  0.8957978  0.57298187]
 [0.8613444  0.54758204 0.67974972]
 [0.71434953 0.19164642 0.44088425]]


Array Attributes

Find the shape, size, and data type of the array you created in the previous task.

In [197]:
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("Data type:",arr1.dtype)
print("Number of dimensions:",arr1.ndim)

print("Shape:",arr2.shape)
print("Size:",arr2.size)
print("Data type:",arr2.dtype)
print("Number of dimensions:",arr2.ndim)

Shape: (41,)
Size: 41
Data type: int64
Number of dimensions: 1
Shape: (3, 3)
Size: 9
Data type: float64
Number of dimensions: 2


Basic Operations

Add 5 to every element of a 1D array.

Multiply two 2D arrays element-wise.

In [199]:
b=5
print(arr1+b)

b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[3,4,5],[1,5,6]])
print(b1*b2)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 3  8 15]
 [ 4 25 36]]


Indexing and Slicing

Create a 5x5 array of integers from 1 to 25. Extract:

The first row.

The last column.

A subarray of the first three rows and first two columns.

In [211]:
arr3=np.arange(1,26).reshape(5,5)
print(arr3)

print(arr3[0:1])
print(arr3[:,4:5])
print(arr3[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[1 2 3 4 5]]
[[ 5]
 [10]
 [15]
 [20]
 [25]]
[[ 1  2]
 [ 6  7]
 [11 12]]


Aggregation

Create a 10-element array of random integers between 10 and 100. Find:

The maximum value.

The minimum value.

The mean and standard deviation.

In [214]:
arr4=np.random.randint(10,101,size=10)
print(arr4)

print(np.max(arr4))
print(np.min(arr4))
print(np.mean(arr4))
print(np.std(arr4))

[11 82 24 53 61 35 10 44 31 90]
90
10
44.1
26.12450956477461


Reshaping

Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [215]:
arr5=np.arange(1,13).reshape(3,4)
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Broadcasting

Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

In [218]:
ones=np.ones((3,3))
print(ones)
arr6=np.array([1,2,3])
print(ones+arr6)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Filtering

Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

In [221]:
arr7=np.arange(1,51)
print(arr7)
print(arr7[arr7%5==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 5 10 15 20 25 30 35 40 45 50]


Matrix Multiplication

Create two 2x2 matrices and perform matrix multiplication.

In [222]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
result=np.dot(a1,a2)
print(result)

[[19 22]
 [43 50]]


Advanced Indexing

Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [226]:
arr8=np.arange(1,17).reshape(4,4)
print(arr8)
print(arr8[[0,1,2,3],[0,1,2,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
